services:
  web:
    build: ./frontend
    image: vidly_web
    ports:
      - 3000:3000

  web-tests:
    image: vidly_web
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm test
  api:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vidly
    volumes:
      - ./backend:/app
    command: ./docker-entrypoint.sh
    
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly:       