name: Generate ASCII Artwork

on:
    push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: install cowsay program
          run: sudo apt-get install cowsay -y

        - name: xecute cowsay CMD
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

        - name: Sleep for 10 seconds
          run: sleep 10


    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
        - name: sleep for 5 seconds
          run: sleep 5

        - name: Test file exists
          run: grep -i "dragon" dragon.txt  

          
    deploy_job_3:
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:
        - name: Read File
          run: cat dragon.txt

        - name: Deploy
          run: echo Deploying ... ... ..
       
